-- +goose Up
-- 任务级 Token 用量：输入/输出、所用 Agent、来源（agent 上报或文本估算）。
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS input_tokens BIGINT NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS output_tokens BIGINT NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS agent TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS token_source TEXT NOT NULL DEFAULT '';

-- +goose Down
ALTER TABLE jobs DROP COLUMN IF EXISTS token_source;
ALTER TABLE jobs DROP COLUMN IF EXISTS agent;
ALTER TABLE jobs DROP COLUMN IF EXISTS output_tokens;
ALTER TABLE jobs DROP COLUMN IF EXISTS input_tokens;
